---
name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  # yamllint disable-line rule:line-length
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions: read-all
env:
  RUSTFLAGS: -Dwarnings
jobs:
  trunk:
    name: trunk.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: trunk check
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
  check-config-docs:
    name: check-config-docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup
        uses: ./.github/actions/setup
      - run: mise run check-config-docs
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup
        uses: ./.github/actions/setup
      - run: mise run lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup
        uses: ./.github/actions/setup
      - run: mise run test
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup
        uses: ./.github/actions/setup
      - run: mise run build
