---
name: release
on:
  push:
    tags:
      - v*.*.*
permissions: read-all
jobs:
  release:
    name: Build & Upload WASM
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust
        # yamllint disable-line rule:line-length
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          toolchain: stable
          targets: wasm32-wasip1
      - name: Rust cache
        # yamllint disable-line rule:line-length
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Run tests
        run: |
          cargo test --lib --target "$(rustc -vV | sed -n 's/^host: //p')"
      - name: Build release
        run: cargo build --release --target wasm32-wasip1
      - name: Upload WASM to release
        # yamllint disable-line rule:line-length
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: |
            target/wasm32-wasip1/release/zellij-status.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
